version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - echo Running pre-build steps...
      # You can add lint/test here if needed
      - npm run lint || true
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --base-href /
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...

artifacts:
  files:
    - '**/*'
  base-directory: dist/product_management  # replace with your Angular dist folder
  discard-paths: no
